name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ builder_publish ]   # optional: trigger deploys from Builder.io webhook
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy:
    # Run for push / repo_dispatch / PR (except PR closed)
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      # Build your Next.js site; this produces the /out folder when using output: 'export'
      - name: Build app
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # REQUIRED: paste this token as a repo secret named AZURE_STATIC_WEB_APPS_API_TOKEN
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

          # Useful for PR comments/status (provided by GitHub automatically)
          repo_token: ${{ secrets.GITHUB_TOKEN }}

          # Explicitly upload artifacts
          action: upload

          # Paths
          app_location: "/"        # Next.js app root (where package.json lives)
          output_location: "out"   # Next.js static export output

          # Include Azure Functions if you have an /api folder (contacts-create, contacts-list, etc.)
          api_location: "api"

          # Helpful hint for Next.js static export deployments
          is_static_export: true

  # Required to tell SWA to tear down PR environments when PRs are closed
  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
